// SPDX-License-Identifier: CC-BY-4.0

== 3. Understanding an NTIA Minimum Elements SPDX SBOM

=== 3.1. Example SPDX Document

Let's look at a basic SPDX Document that contains the NTIA Minimum Elements data for a simple piece of software.

This is an SBOM I've created for a fictional piece of software, the Frobozz Text Editor.
It contains a single third-party component, a spellchecker that is packaged into and distributed together with the main text editor.

Here's the SPDX Document, in tag-value format:

.sample.spdx
----
SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: Frobozz Editor SBOM
DocumentNamespace: https://swinslow.net/spdx-ntia-sbom-howto/sample1-v1
Creator: Person: Steve Winslow (steve@swinslow.net)
Created: 2023-03-26T18:00:00Z

PackageName: Frobozz Text Editor
SPDXID: SPDXRef-Package-Frobozz
PackageVersion: v1.2.3
PackageSupplier: Organization: Frobozz Magic Software Company
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageChecksum: SHA256: eec9e126fb075d505869f443587cf48173f3da1d817ae47cb8c1a676e47d8377
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-Frobozz

PackageName: Spellchecker of Yendor
SPDXID: SPDXRef-Package-Yendor
PackageVersion: v3.5-beta2
PackageSupplier: Person: Wizard of Yendor
FilesAnalyzed: false
PackageDownloadLocation: NOASSERTION
PackageChecksum: SHA256: 0fa8a1044f6ad57d84073eda3701bfa2805046e7862fe85c41ea28166d1676f6
Relationship: SPDXRef-Package-Frobozz CONTAINS SPDXRef-Package-Yendor
----

This SPDX Document begins with the mandatory Document Creation Information section, and is followed by two Package Information sections--one for the text editor, and one for its packaged spellchecker component.

Let's walk through it line by line.

=== 3.2. Document Creation Information Section

Lines 1-7 form the Document Creation Information section, which is essentially a "file header" defining data about the SPDX Document itself.

----
SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: Frobozz Editor SBOM
----

The first four lines are required by the SPDX Document format, and are not part of the NTIA Minimum Elements.
These lines indicate:

* ``SPDXVersion``: the version of the SPDX specification being used (here, ``2.3``)
* ``DataLicense``: the license applicable to the SPDX Document itself (``CC0-1.0``, per https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#62-data-license-field[section 6.2 of the SPDX spec])
* ``SPDXID``: the "local" part of the unique SPDX identifier referring to the SPDX Document itself (``SPDXRef-DOCUMENT``); and
* ``DocumentName``: a user-defined plain language name to refer to the SPDX document

``SPDXVersion``, ``DataLicense`` and ``SPDXID`` will be identical in every SPDX Document you create--assuming you're creating a tag-value SPDX 2.3 Document.
``DocumentName`` is also required by the SPDX specification to be present, but can contain whatever value you'd like.

----
DocumentNamespace: https://swinslow.net/spdx-ntia-sbom-howto/sample1-v1
Creator: Person: Steve Winslow (steve@swinslow.net)
Created: 2023-03-26T18:00:00Z
----

The next three lines cover the remainder of the required elements for the Document Creation Information section. These are also part of the NTIA Minimum Elements:

* ``DocumentNamespace``: see subsection **TBD** for more information; this is part of the _Other Unique Identifiers_ NTIA element
* ``Creator``: This can be either a ``Person``, ``Organization`` or ``Tool``, with optional email address in parentheses; this is the _Author of SBOM Data_ NTIA element
* ``Created``: This is the date of the creation of the SBOM, expressed in UTC time per the https://en.wikipedia.org/wiki/ISO_8601[ISO 8601 format]; this is the _Timestamp_ NTIA element

These seven lines comprise the entirety of the required fields for the Document Creation Information section for an SPDX 2.x Document, and also cover 2 1/2 of the NTIA Minimum Elements.

=== 3.3. Package Information Section - primary package




