// SPDX-License-Identifier: CC-BY-4.0

== 3. Understanding an NTIA Minimum Elements SPDX SBOM

=== 3.1. Example SPDX Document

Let's look at a basic SPDX Document that contains the NTIA Minimum Elements data for a simple piece of software.

This is an SBOM I've created for a fictional piece of software, the Frobozz Text Editor.
It contains a single third-party component, a spellchecker that is packaged into and distributed together with the main text editor.

Here's the SPDX Document, in tag-value format:

.samples/sample.spdx
----
SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: Frobozz Editor SBOM
DocumentNamespace: https://swinslow.net/spdx-ntia-sbom-howto/sample1-v1
Creator: Person: Steve Winslow (steve@swinslow.net)
Created: 2023-03-26T18:00:00Z

PackageName: Frobozz Text Editor
SPDXID: SPDXRef-Package-Frobozz
PackageVersion: v1.2.3
PackageSupplier: Organization: Frobozz Magic Software Company
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-Frobozz

PackageName: Spellchecker of Yendor
SPDXID: SPDXRef-Package-Yendor
PackageVersion: v3.5-beta2
PackageSupplier: Person: Wizard of Yendor
FilesAnalyzed: false
PackageDownloadLocation: NOASSERTION
Relationship: SPDXRef-Package-Frobozz CONTAINS SPDXRef-Package-Yendor
----

This SPDX Document begins with the mandatory Document Creation information section, and is followed by two Package information sections--one for the text editor, and one for its packaged spellchecker component.

Let's walk through it line by line.

=== 3.2. Document Creation Information Section

Lines 1-7 form the Document Creation information section, which is essentially a "file header" defining data about the SPDX Document itself.

----
SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: Frobozz Editor SBOM
----

The first four lines are required by the SPDX Document format, and are not part of the NTIA Minimum Elements.
These lines indicate:

* ``SPDXVersion``: the version of the SPDX specification being used (here, ``2.3``)
* ``DataLicense``: the license applicable to the SPDX Document itself (``CC0-1.0``, per https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#62-data-license-field[section 6.2 of the SPDX spec])
* ``SPDXID``: the "local" part of the unique SPDX identifier referring to the SPDX Document itself (``SPDXRef-DOCUMENT``); and
* ``DocumentName``: a user-defined plain language name to refer to the SPDX document

``SPDXVersion``, ``DataLicense`` and ``SPDXID`` will be identical in every SPDX Document you create--assuming you're creating a tag-value SPDX 2.3 Document.
``DocumentName`` is also required by the SPDX specification to be present, but can contain whatever value you'd like.

----
DocumentNamespace: https://swinslow.net/spdx-ntia-sbom-howto/sample1-v1
Creator: Person: Steve Winslow (steve@swinslow.net)
Created: 2023-03-26T18:00:00Z
----

The next three lines cover the remainder of the required elements for the Document Creation information section.
These are also part of the NTIA Minimum Elements:

* ``DocumentNamespace``: see Part 2.**TBD** for more information; this is part of the _Other Unique Identifiers_ NTIA element
* ``Creator``: one or more of ``Person``, ``Organization`` or ``Tool`` that created this SPDX Document, with optional email address in parentheses for a Person or Organization; this is the _Author of SBOM Data_ NTIA element
* ``Created``: the date-time of the creation of the SBOM, expressed in UTC per the https://en.wikipedia.org/wiki/ISO_8601[ISO 8601 format]; this is the _Timestamp_ NTIA element

These seven lines comprise the entirety of the required fields for the Document Creation information section for an SPDX 2.x Document, and also cover 2 1/2 of the NTIA Minimum Elements.

=== 3.3. Package Information Section and Relationship - primary package

The next block (lines 9-15) forms the Package information section for the primary Package being described by the SPDX Document: the Frobozz Text Editor.
It also includes a ``DESCRIBES`` Relationship, stating that this SPDX Document is principally describing the text editor Package.

----
PackageName: Frobozz Text Editor
----

For SPDX Documents in tag-value format, a new Package information section always begins with the ``PackageName`` tag.
This line indicates:

* ``PackageName``: the full human-readable name for the Package, as given by the Package's originator; this is the _Component Name_ NTIA element

----
SPDXID: SPDXRef-Package-Frobozz
----

The next line indicates:

* ``SPDXID``: together with ``DocumentNamespace``, this forms a unique addressable identifier for this Package, as described in 2.**TBD**; this is the other part of the _Other Unique Identifiers_ NTIA element

The ``SPDXID`` will always begin with ``SPDXRef-``, followed by a unique string containing letters, numbers, ``.`` and/or ``-``.
The ``SPDXID`` value must be unique within this SPDX Document.

----
PackageVersion: v1.2.3
PackageSupplier: Organization: Frobozz Magic Software Company
----

These two lines indicate:

* ``PackageVersion``: The version of the Package, as specified by its supplier; this is the _Version of the Component_ NTIA element
* ``PackageSupplier``: The identity of the direct supplier of the Package, as a ``Person`` or ``Organization`` similar to the SPDX Document ``Creator`` element described above; this is the _Supplier Name_ NTIA element

----
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-Package-Frobozz
----

The next three lines are not part of the NTIA Minimum Elements, but are instead required by the SPDX 2.3 specification.
These two lines indicate:

* ``PackageDownloadLocation``: the URL or version control system location from which the Package can be downloaded, if any
* ``FilesAnalyzed``: a boolean specifying whether or not the SPDX Document includes File information sections for the Files comprising this Package
* ``Relationship``: with the ``DESCRIBES`` relationship type, indicates that the SPDX Document is primarily describing the text editor Package

A minimal SBOM meeting the NTIA Minimal Elements requirements does not need to include File information sections, so we'll leave ``FilesAnalyzed`` as ``false``.

If we know the ``PackageDownloadLocation`` for this version of the Package, we can specify the URL, but there's no need to do so.
We can leave it as ``NOASSERTION`` to indicate that we (as the SPDX Document creator) are not making any attempt to specify it; or if we knew that there is no download location whatsoever, we could also specify ``NONE``.

Line 15 is technically part of a Relationship information section, but it can in fact appear anywhere in the SPDX Document after the initial Document Creation information section.
Each SPDX Document that contains more than one Package must include at least one ``DESCRIBES`` Relationship, in order to specify which Package is the primary one being described by this SPDX Document.

=== 3.4. Package Information Section and Relationship - contained dependency

The elements listed in subsections 3.2 and 3.3 above are actually all that is required by the NTIA Minimum Elements and the SPDX specification format, for a primary Package that contains no dependencies.

For this example, we're assuming that the text editor includes exactly one dependency, a separate spellchecker component obtained from a third party.
The final block (lines 17-23) describes this dependency.

Most of the fields have an identical meaning and structure as those used in the Package information section for the primary Package.
Only the final line has a different structure:

----
Relationship: SPDXRef-Package-Frobozz CONTAINS SPDXRef-Package-Yendor
----

While this is also a Relationship information line as for the prior Package, this one instead has a ``CONTAINS`` relationship type, indicating:

* ``Relationship``: with the ``CONTAINS`` relationship type, indicates that the Package with the ID specified on the left side contains the Package with the ID specified on the right side; this is the _Dependency Relationship_ NTIA element

Assuming that this spellchecker Package is the only dependency contained in the text editor Package, we are all done.
This SPDX Document contains all of the NTIA Minimum Elements for an SBOM.

=== 3.5. Summary of required fields

The following table summarizes the SPDX fields that correspond to the NTIA Minimum Elements fields.

.NTIA Minimum Elements and SPDX 2.3 fields
[cols="1,1,1"]
|===
|NTIA element name |SPDX 2.3 field name |SPDX 2.3 specification reference

|Supplier Name
|``PackageSupplier``
|https://spdx.github.io/spdx-spec/v2.3/package-information/#75-package-supplier-field[Section 7.5]

|Component Name
|``PackageName``
|https://spdx.github.io/spdx-spec/v2.3/package-information/#71-package-name-field[Section 7.1]

|Version of the Component
|``PackageVersion``
|https://spdx.github.io/spdx-spec/v2.3/package-information/#73-package-version-field[Section 7.3]

|Other Unique Identifiers
|``DocumentNamespace``, ``SPDXID``
|https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#65-spdx-document-namespace-field[Section 6.5], https://spdx.github.io/spdx-spec/v2.3/package-information/#72-package-spdx-identifier-field[Section 7.2]

|Dependency Relationship
|``Relationship`` (``CONTAINS``)
|https://spdx.github.io/spdx-spec/v2.3/relationships-between-SPDX-elements/#111-relationship-field[Section 11.1]

|Author of SBOM Data
|``Creator``
|https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#68-creator-field[Section 6.8]

|Timestamp
|``Created``
|https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#69-created-field[Section 6.9]
|===

Additionally, the following table summarizes the other SPDX fields that are required as mandatory fields per the SPDX spec, which do not correspond to the NTIA Minimum Elements.

.Other mandatory SPDX 2.3 fields
[cols="1,1,1"]
|===
|SPDX 2.3 field name |Value |SPDX 2.3 specification reference

|``SPDXVersion``
|``SPDX-2.3``
|https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#61-spdx-version-field[Section 6.1]

|``DataLicense``
|``CC0-1.0``
|https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#62-data-license-field[Section 6.2]

|``SPDXID`` (for Document)
|``SPDXRef-DOCUMENT``
|https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#63-spdx-identifier-field[Section 6.3]

|``DocumentName``
|user-defined name of SPDX Document
|https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#64-document-name-field[Section 6.4]

|``PackageDownloadLocation``
|``NOASSERTION`` or URL / VCS location
|https://spdx.github.io/spdx-spec/v2.3/package-information/#77-package-download-location-field[Section 7.7]

|``FilesAnalyzed``
|``false`` (unless including all File information sections)
|https://spdx.github.io/spdx-spec/v2.3/package-information/#78-files-analyzed-field[Section 7.8]

|``Relationship`` (``DESCRIBES``, for primary Package)
|``SPDXRef-DOCUMENT`` on left side, ID of primary Package on right side
|https://spdx.github.io/spdx-spec/v2.3/relationships-between-SPDX-elements/#111-relationship-field[Section 11.1]
|===
