// SPDX-License-Identifier: CC-BY-4.0

== 4. Creating an NTIA Minimum Elements SPDX SBOM

The next part of this HOWTO describes a few different processes for creating an NTIA Minimum Elements SBOM in SPDX format, including some additional considerations for your own software.

=== 4.1. Manual creation via text file

The simplest way to get started with creating an SBOM is to do it manually.
An SPDX Document in tag-value format is nothing more than a text file with particular fields.

Below is a template that you can copy and use to create your own SPDX 2.3 SBOM for your own software.

==== 4.1.1. SPDX 2.3 template for NTIA Minimum Elements SBOM

Here are a few rules for using this template:
* SPDX tag-value files typically end with the ``.spdx`` file extension.
* Lines beginning with ``#`` are comments, and are included in the template just as guidance; these can be omitted.
* Bracketed portions of text explain the values that should be used for those lines; refer back to Part 3 of this HOWTO for more details about the meanings of each line.
* The remaining lines without brackets should be reproduced as-is, for this minimal SBOM template.
* The bottom block of text in the template (lines 23-29) should be reproduced with a separate copy for each dependency included in the primary Package; see also the notes following the template below regarding additional and unknown dependencies.

.samples/template.spdx
----
# Document Creation information section

SPDXVersion: SPDX-2.3
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: [Name of SPDX Document]
DocumentNamespace: [URI for unique namespace for this SPDX Document]
Creator: [SBOM creator, in one of the following forms][Option 1: Person: Full Name][Option 2: Organization: Company Name]
Created: [SBOM creation date and time in UTC ISO 8601 format, e.g. YYYY-MM-DDThh-mm-ssZ]

# Package information section - primary Package

PackageName: [Name of primary Package]
SPDXID: [Unique ID for primary Package, beginning with SPDXRef- followed by letters, numbers, . and -]
PackageVersion: [Version of primary Package]
PackageSupplier: [Supplier of primary Package, in one of the following forms][Option 1: Person: Full Name][Option 2: Organization: Company Name]
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
Relationship: SPDXRef-DOCUMENT DESCRIBES [ID for primary Package specified above]

# Package information section - one for each dependency contained in primary Package

PackageName: [Name of dependency]
SPDXID: [Unique ID for dependency, following the ID rules described above]
PackageVersion: [Version of dependency]
PackageSupplier: [Supplier of dependency, in one of the following forms][Option 1: Person: Full Name][Option 2: Organization: Company Name]
FilesAnalyzed: false
PackageDownloadLocation: NOASSERTION
Relationship: [ID for primary Package] CONTAINS [ID for dependency]
----

==== 4.1.2. Additional subdependencies

According to the NTIA guidance on https://www.ntia.doc.gov/files/ntia/publications/sbom_minimum_elements_report.pdf[Minimum Elements for an SBOM], an SBOM

[quote,'NTIA Minimum Elements p. 12, "Depth"']
should contain all primary (top level) components, with all their transitive dependencies listed. At a minimum, all top-level dependencies [.underline]#must# be listed with enough detail to seek out the transitive dependencies recursively.

This indicates that although it is only _required_ that the top-level dependencies be specified in an SBOM, it is _preferred_ that it describe ALL dependencies, if possible.
This would include both:

* _direct dependencies_ (aka "top-level"), which are directly leveraged by the primary software; and
* _indirect dependencies_ (aka "transitive" or "subdependencies"), which are leveraged by another direct or indirect dependency.

Ideally, then, the SBOM should include a Package information section for each direct AND indirect dependency, if possible.

* For a _direct dependency_, the ``Relationship`` line would have the primary software Package's ID on the left side of the ``CONTAINS`` field.
* For an _indirect dependency_, the ``Relationship`` line would have the parent dependency Package's ID on the left side of the ``CONTAINS`` field.

Keep in mind that it is possible for a Package to be a subdependency of two (or more!) other dependencies, or for it to be both a direct and indirect dependency.
In any of these cases, multiple Relationship lines can be used to specify the various dependency relationships.

==== 4.1.3. Unknown dependencies

The NTIA guidance also states

[quote,'NTIA Minimum Elements p. 12, "Known Unknowns"']
For instances in which the full dependency graph is not enumerated in the SBOM, the SBOM author [.underline]#must# explicitly identify "known unknowns."

If your SBOM contains a Package section with corresponding Relationships for all contained dependencies, then you are all set; you have enumerated the full dependency graph.

But if you know that you have not listed all _indirect_ dependencies contained in your software, that's okay under the NTIA Minimum Elements (as long as all _direct_ dependencies are listed).
It just means that you need to include a statement explicitly indicating that there are "known unknowns".

In SPDX 2.3, this is done with using the following line for each direct dependency (assuming for this example that the direct dependency Package's specified SPDXID is ``SPDXRef-Package-Dep1``)

----
Relationship: SPDXRef-Package-Dep1 CONTAINS NOASSERTION
----

The ``NOASSERTION`` special identifier indicates that the SBOM Document's author is explicitly _not asserting_ whether there are other indirect dependencies that might be contained within the ``SPDXRef-Package-Dep1`` dependency's Package.

So if you haven't described in the SBOM all _indirect_ dependencies, be sure to include this ``CONTAINS NOASSERTION`` relationship line for each such _direct_ dependency.

=== 4.2. Manual creation via SwiftBOM

Rather than creating an SPDX Document via a text file from scratch, there are templating tools that can assist with filling in the fields manually and formatting the data as required by SPDX.

https://github.com/CERTCC[The CERT Coordination Center at Carnegie Mellon University's Software Engineering Institute] hosts a tool called https://democert.org/sbom/[SwiftBOM] (with source code available on GitHub at https://github.com/CERTCC/SBOM under the MIT license).
This is a proof of concept SBOM generator that shows the fields required to be filled in by the SPDX Document creator in a simple form.
After the form is filled in, an SPDX SBOM containing the NTIA Minimum Elements can be downloaded (assuming that the fields are filled in correctly.

Note that the generated SBOM may not be "optimized" for human readability.
For example, it generates SPDX IDs for the Package information sections using hashes, which are fine for automated parsing but may make it more challenging for a human reader to fully understand the SBOM.
This tradeoff between tooling-assisted creation of SBOMs (easier but less readable) and manual human creation of SBOMs (more readable but more tedious and error-prone) is something that SBOM creators will need to consider when designing their processes.

=== 4.3. Automated creation using tooling [TO BE COMPLETED]

*To get input from SPDX tech team regarding an automated tooling example*

=== 4.4. Additional details and Optional recommended fields [TO BE COMPLETED]

*To add details about the following, based on NTIA guidance:*

* hash and PackageChecksum
* other dependency and relationship types
* frequency
* distribution and delivery
* access control
* license info

